Repository sesac-project-E/mealsac, pull requests merged in 2023-10, with the labels that each got.

#223 Refactor: 식당 목록 페이지 css 수정
  src/static/css/restaurantList.css
  src/static/js/restaurantList.js
Labels: 🎨 Style, ☀️ Front-End

#224 Docs: README 이미지 수정
  README.md
  src/static/img/docs.png
  src/static/img/mealsac_ERD.png
  src/static/img/readmeImage/functionSpecification.png
  src/static/img/readmeImage/mealsac_ERD.png
  src/static/img/readmeImage/readmelogo.png
Labels: 📄 Docs

#232 Fix: aws 배포시 YAMLSyntaxError 애러 발생해 작성한 swaggerdoc 제거
  src/routes/reviewRouter.js
Labels: 🚨 Bug

#234 Disign : reply가 가로 이상으로 넘칠때 UX 수정
  src/static/css/boardPost.css
  src/static/js/post.js
Labels: 🎨 Style, ☀️ Front-End

#236 Fix: 상세한 버그들 수정
  src/controllers/postController.js
  src/static/css/boardPost.css
  src/static/css/headerNfooter.css
  src/static/css/restaurantDetail.css
  src/static/js/boardModify.js
  src/static/js/boardWrite.js
  src/static/js/index.js
  src/static/js/post.js
  src/views/boardPost/index.ejs
  src/views/index.ejs
  src/views/restaurantDetail/index.ejs
Labels: 🚨 Bug

#237 Fix: 로그인 하지 않고 게시글 상세 페이지 진입 시 userInfo is not defined 에러 수정
  src/controllers/postController.js
Labels: 🚨 Bug

#238 #235 fix: 비 로그인 유저 게시판 상세페이지 진입 에러 수정
  src/controllers/postController.js
  src/views/boardPost/index.ejs
Labels: 🚨 Bug

#239 Fix: 게시글 상세페이지 버그 수정
  src/controllers/postController.js
  src/controllers/reviewController.js
  src/views/boardPost/index.ejs
Labels: 🚨 Bug

#240 Fix: AWS 배포 후에 나타나는 게시글 버그 수정
  src/views/boardPost/index.ejs
Labels: 🚨 Bug

#241 Fix: aws 배포 시 userInfo is not defined 에러 발생하여 userInfo가 세션에 없다면 false를 반환하도록 수정
  src/controllers/postController.js
Labels: 🚨 Bug

#242 Fix: 게시판 버그, 로그인 버그 수정
  src/controllers/postController.js
  src/controllers/userController.js
  src/routes/userRouter.js
  src/static/js/board.js
  src/static/js/boardModify.js
  src/static/js/boardWrite.js
  src/static/js/header.js
  src/static/js/login.js
  src/static/js/post.js
  src/views/boardPost/index.ejs
  src/views/common/header.ejs
Labels: 🚨 Bug, 📭 API, ☀️ Front-End, 🌙 Back-End

#243 Fix: 발견한 버그들 수정
  src/controllers/oauthController.js
  src/controllers/userController.js
  src/static/js/header.js
  src/static/js/restaurantDetail.js
  src/views/common/restaurantComponent.ejs
  src/views/index.ejs
Labels: 🚨 Bug

#249 Feat: 메뉴 검색 페이지 구현
  src/controllers/restaurantController.js
  src/routes/indexRouter.js
  src/routes/restaurantRouter.js
  src/static/css/searchMenu.css
  src/static/js/index.js
  src/static/js/searchMenu.js
  src/views/index.ejs
  src/views/searchMenu/index.ejs
Labels: ☀️ Front-End

#251 Fix: 카카오 로그인 시 회원정보 수정 버튼 보이지 않도록 수정
  src/controllers/oauthController.js
  src/static/js/mypage.js
  src/views/mypage/index.ejs
Labels: 🚨 Bug

#254 Fix: 작은 버그들 수정, Comment: 불필요한 주석, 코드 삭제
  package.json
  restaurant.json
  src/controllers/commentController.js
  src/controllers/oauthController.js
  src/controllers/restaurantController.js
  src/controllers/reviewController.js
  src/controllers/tagController.js
  src/controllers/userController.js
  src/models/Post.js
  src/models/comment.js
  src/routes/commentRouter.js
  src/routes/index.js
  src/routes/indexRouter.js
  src/routes/menuRouter.js
  src/routes/oauthRouter.js
  src/routes/restaurantRouter.js
  src/routes/tagRouter.js
  src/routes/userRouter.js
  src/static/css/boardPost.css
  src/static/css/restaurantList.css
  src/static/js/boardModify.js
  src/static/js/boardWrite.js
  src/static/js/login.js
  src/static/js/mypage.js
  src/static/js/post.js
  src/static/js/random.js
  src/static/js/register.js
  src/static/js/restaurantList.js
  src/utils/formatDate.js
  src/utils/restaurantType.js
  src/views/404.ejs
  src/views/board/index.ejs
  src/views/boardModify/index.ejs
  src/views/boardPost/index.ejs
  src/views/boardWrite/index.ejs
  src/views/common/commonHead.ejs
  src/views/common/header.ejs
  src/views/index.ejs
  src/views/login/index.ejs
  src/views/mypage/index.ejs
  src/views/profile/index.ejs
  src/views/random/index.ejs
  src/views/register/index.ejs
  src/views/restaurantList/index.ejs
  src/views/searchMenu/index.ejs
Labels: 🚨 Bug

#255 Fix: 게시판 페이지 버그 수정
  src/routes/indexRouter.js
  src/static/css/board.css
  src/static/js/board.js
  src/views/board/index.ejs
Labels: 🚨 Bug, 🎨 Style

#256 Design: 식당 목록에서 식당 정보 가운데 정렬하도록 수정
  src/static/css/restaurantList.css
  src/static/css/searchMenu.css
Labels: 🎨 Style, ☀️ Front-End

#259 Fix/#235/bugfix
  src/routes/indexRouter.js
  src/static/css/board.css
  src/static/css/boardModify.css
  src/static/css/boardPost.css
  src/static/css/boardWrite.css
  src/static/css/headerNfooter.css
  src/static/css/login.css
  src/static/css/mypage.css
  src/static/css/restaurantList.css
  src/static/css/searchMenu.css
  src/static/img/hamburger.png
  src/static/js/board.js
  src/static/js/mypage.js
  src/static/js/restaurantDetail.js
  src/views/board/index.ejs
  src/views/boardWrite/index.ejs
  src/views/mypage/index.ejs
  src/views/restaurantDetail/index.ejs
  src/views/restaurantList/index.ejs
Labels: 🚨 Bug

#261 fix: http의 경우에는 navigator.clipboard api를 지원하지 않아 모바일 이외에 전화하기 버튼 클릭 시…
  src/static/js/restaurantDetail.js
Labels: 🚨 Bug
